name: Make draft release

on:
  workflow_dispatch:

jobs:
  # This job builds the jar AND creates the draft release
  build-and-release:
    permissions:
      contents: write
    uses: qupath/actions/.github/workflows/github-release.yml@main
    with:
      java-version: "25"
      # This ensures the QuPath workflow knows where your shadowJar is
      build-path: "build/libs/*-all.jar" 
      gradle-args: "shadowJar"
